import type { Question, DiagnosisResult, DiagnosisIntro } from "./types";

export const colorIntro: DiagnosisIntro = {
  headline: "色の試練",
  problem: "色の試練が あなたの前に\n立ちはだかった！\n\n同じ白シャツでも カラー適性が合えば「清潔感+20」。\n合わなければ「色気-15」。\n色という属性装備を間違えるだけで\n顔色のステータスは 大幅にダウンする。",
  solution: "この試練をクリアすれば\nあなたのパーソナルカラーが判明し\nカラー装備適性が解放される。\n肌・髪・瞳に映える\n最強の色パレットが手に入る。",
  benefits: [
    { icon: "✨", text: "顔色ステータスが跳ね上がり 清潔感・健康感が最大化される" },
    { icon: "🗡️", text: "服・ネクタイ・アウターの色装備で 迷わなくなる" },
    { icon: "🛡️", text: "「疲れてる？」のデバフ攻撃を 完全に防御できる" },
    { icon: "⚡", text: "仕事・対人の印象値が レベルアップする" },
  ],
  closingHook: "7 STAGES / 所要時間: 2分",
};

export const colorQuestions: Question[] = [
  {
    id: "c1",
    text: "白いワイシャツを着たとき、顔色が良く見えるのはどのタイプ？",
    options: [
      { label: "アイボリーやクリーム系の白", value: "a", score: { spring: 2, summer: 0, autumn: 1, winter: 0 } },
      { label: "薄いブルーがかった白", value: "b", score: { spring: 0, summer: 2, autumn: 0, winter: 0 } },
      { label: "生成り・オフホワイト", value: "c", score: { spring: 0, summer: 0, autumn: 2, winter: 0 } },
      { label: "真っ白（ピュアホワイト）", value: "d", score: { spring: 0, summer: 0, autumn: 0, winter: 2 } },
    ],
  },
  {
    id: "c2",
    text: "腕時計やアクセサリーを着けたとき、肌に映えると感じるのは？",
    options: [
      { label: "明るいゴールド（イエローゴールド）", value: "a", score: { spring: 2, summer: 0, autumn: 1, winter: 0 } },
      { label: "マットなシルバーやホワイトゴールド", value: "b", score: { spring: 0, summer: 2, autumn: 0, winter: 0 } },
      { label: "アンティーク調のゴールド・ブロンズ", value: "c", score: { spring: 0, summer: 0, autumn: 2, winter: 0 } },
      { label: "光沢のあるシルバーやプラチナ", value: "d", score: { spring: 0, summer: 0, autumn: 0, winter: 2 } },
    ],
  },
  {
    id: "c3",
    text: "髭剃りのあと鏡で見ると、肌の色味はどう見える？",
    options: [
      { label: "黄味がかっていて血色がいい", value: "a", score: { spring: 2, summer: 0, autumn: 1, winter: 0 } },
      { label: "ピンクがかって明るい", value: "b", score: { spring: 0, summer: 2, autumn: 0, winter: 1 } },
      { label: "黄味が強く、マットな質感", value: "c", score: { spring: 1, summer: 0, autumn: 2, winter: 0 } },
      { label: "青白い・色白でコントラストが強い", value: "d", score: { spring: 0, summer: 0, autumn: 0, winter: 2 } },
    ],
  },
  {
    id: "c4",
    text: "夏に日焼けしたあと、肌はどう変化する？",
    options: [
      { label: "少し赤くなるが、すぐ元の肌色に戻る", value: "a", score: { spring: 1, summer: 2, autumn: 0, winter: 0 } },
      { label: "赤くなってから薄く焼ける", value: "b", score: { spring: 1, summer: 0, autumn: 0, winter: 2 } },
      { label: "すぐに黒く焼けて、なかなか戻らない", value: "c", score: { spring: 0, summer: 0, autumn: 2, winter: 0 } },
      { label: "あまり焼けず、赤くなって白い肌に戻る", value: "d", score: { spring: 0, summer: 1, autumn: 0, winter: 1 } },
    ],
  },
  {
    id: "c5",
    text: "スーツやジャケットの色で、周りから「似合う」と言われるのは？",
    options: [
      { label: "明るいベージュ・キャメル系", value: "a", score: { spring: 2, summer: 0, autumn: 1, winter: 0 } },
      { label: "ライトグレー・パウダーブルー系", value: "b", score: { spring: 0, summer: 2, autumn: 0, winter: 0 } },
      { label: "ダークブラウン・カーキ系", value: "c", score: { spring: 0, summer: 0, autumn: 2, winter: 0 } },
      { label: "ブラック・チャコール・ネイビー系", value: "d", score: { spring: 0, summer: 0, autumn: 0, winter: 2 } },
    ],
  },
  {
    id: "c6",
    text: "自分の地毛の色を光の下で見ると、どう見える？",
    options: [
      { label: "明るめの茶色・光に透ける感じ", value: "a", score: { spring: 2, summer: 0, autumn: 1, winter: 0 } },
      { label: "アッシュがかった柔らかい黒", value: "b", score: { spring: 0, summer: 2, autumn: 0, winter: 0 } },
      { label: "暗めのこげ茶・マットな質感", value: "c", score: { spring: 0, summer: 0, autumn: 2, winter: 0 } },
      { label: "真っ黒でツヤがある", value: "d", score: { spring: 0, summer: 0, autumn: 0, winter: 2 } },
    ],
  },
  {
    id: "c7",
    text: "ネクタイやマフラーで、顔色が明るく見えると感じる色は？",
    options: [
      { label: "コーラルピンク・オレンジ系の暖色", value: "a", score: { spring: 2, summer: 0, autumn: 0, winter: 0 } },
      { label: "ラベンダー・ローズ系のくすんだ色", value: "b", score: { spring: 0, summer: 2, autumn: 0, winter: 0 } },
      { label: "テラコッタ・マスタード系の深い暖色", value: "c", score: { spring: 0, summer: 0, autumn: 2, winter: 0 } },
      { label: "ロイヤルブルー・ワインレッド等の鮮やかな色", value: "d", score: { spring: 0, summer: 0, autumn: 0, winter: 2 } },
    ],
  },
];

export const colorResults: Record<string, DiagnosisResult> = {
  spring: {
    type: "spring",
    label: "スプリング（イエベ春）",
    description: "明るく暖かみのある色が似合う。フレッシュで若々しい印象を活かすカラーリング。",
    stats: { 存在感: 65, 清潔感: 80, 信頼感: 70, 色気: 60, 親しみ: 85 },
    features: [
      "肌に黄味があり、ツヤっぽい",
      "瞳がキラキラと明るい",
      "明るい色を着ると顔色が良くなる",
      "ゴールドアクセが似合う",
    ],
    fashion: [
      { item: "キャメル・コーラルピンク", reason: "黄味のある肌と同系統の暖色が、顔色を明るく健康的に見せる", stat: "親しみ+15" },
      { item: "アイボリー・ライトベージュ", reason: "肌のツヤ感と明るいトーンが調和し、清潔感が際立つ", stat: "清潔感+20" },
      { item: "明るいオレンジ・サーモンピンク", reason: "血色の良い肌にビタミンカラーが映え、活発で好印象に", stat: "存在感+15" },
      { item: "黄緑・ターコイズブルー", reason: "黄味ベースの肌にフレッシュな差し色が入り、顔が引き締まる", stat: "信頼感+10" },
      { item: "ブラウン系のグラデーション", reason: "肌・髪・瞳の暖かいトーンと統一感が出て洗練された印象になる", stat: "色気+15" },
    ],
    ngItems: [
      { item: "真っ黒のワントーンコーデ", reason: "明るい肌色と黒の強いコントラストで、顔色が悪く疲れて見える", stat: "清潔感-15" },
      { item: "青みの強いグレー", reason: "黄味の肌にブルー系が乗ると、肌がくすんで不健康な印象になる", stat: "親しみ-10" },
      { item: "ネイビー×白の寒色コーデ", reason: "暖色系の肌色と冷たい配色が喧嘩し、顔だけ浮いて見える", stat: "信頼感-10" },
      { item: "くすんだ暗い色全般", reason: "明るい肌のフレッシュさが殺され、老けた印象になる", stat: "存在感-15" },
    ],
    celebrities: ["木村拓哉", "佐藤健", "岡田将生"],
    products: [
      {
        name: "キャメルレザー 長財布",
        description: "イエベ春の肌に映えるキャメルカラー。温かみのあるゴールド金具が黄味肌と調和し、手元を華やかに演出。大切な方への贈り物に最適な上質イタリアンレザー仕上げ。",
        price: "¥25,000〜",
        affiliateUrl: "https://example.com/affiliate/spring-camel-wallet-gift",
        tag: "誕生日に",
      },
      {
        name: "コーラルピンク カシミヤマフラー",
        description: "イエベ春の血色を引き立てるコーラルカラー。顔まわりに巻くだけで顔色が明るくなり、健康的で若々しい印象に。クリスマスギフトに喜ばれる極上の肌触り。",
        price: "¥18,000〜",
        affiliateUrl: "https://example.com/affiliate/spring-coral-cashmere-gift",
        tag: "クリスマスに",
      },
      {
        name: "ゴールドフレーム サングラス",
        description: "イエベ春と相性抜群のイエローゴールドフレーム。明るいレンズカラーが肌のツヤ感を引き立て、フレッシュな印象をキープ。記念日の特別なプレゼントにふさわしい一品。",
        price: "¥32,000〜",
        affiliateUrl: "https://example.com/affiliate/spring-gold-sunglasses-gift",
        tag: "記念日に",
      },
    ],
    salonCta: {
      heading: "プロのカラー診断でベストカラーを見つける",
      description: "スプリングタイプは明るく暖かい色が得意。プロの診断で、あなたに似合うキャメルやコーラルの最適なトーンを見つけましょう。",
      buttonLabel: "近くのサロンを探す",
      url: "https://example.com/salon/color-diagnosis",
    },
  },
  summer: {
    type: "summer",
    label: "サマー（ブルベ夏）",
    description: "涼しげで柔らかい色が似合う。上品で知的な印象を活かすカラーリング。",
    stats: { 存在感: 60, 清潔感: 85, 信頼感: 80, 色気: 65, 親しみ: 70 },
    features: [
      "肌にピンク味があり透明感がある",
      "瞳が柔らかいグレーや赤みのある茶色",
      "パステルカラーが映える",
      "シルバーアクセが似合う",
    ],
    fashion: [
      { item: "ラベンダー・ローズピンク", reason: "ピンク味のある肌と同系統の青みカラーが、透明感を引き出す", stat: "色気+15" },
      { item: "スカイブルー・ペールブルー", reason: "涼しげな肌色に淡いブルーが溶け込み、知的で上品な印象に", stat: "信頼感+20" },
      { item: "グレー・ブルーグレー", reason: "柔らかい肌の質感とスモーキーな色味が調和し、洗練されて見える", stat: "清潔感+15" },
      { item: "ネイビー・ベビーピンク", reason: "ブルーベースの肌にネイビーが映え、ピンクが血色感を足す", stat: "存在感+10" },
      { item: "オフホワイト", reason: "真っ白より少しくすんだ白が肌のトーンと馴染み、顔色が明るくなる", stat: "親しみ+15" },
    ],
    ngItems: [
      { item: "オレンジやキャメル", reason: "ピンク肌に黄味の強い暖色が乗ると、肌がくすんで黄ばんで見える", stat: "清潔感-15" },
      { item: "鮮やかすぎる黄色", reason: "ブルーベースの肌と黄色の相性が悪く、顔色が不健康に見える", stat: "信頼感-10" },
      { item: "カーキ", reason: "涼しげな肌色にアーストーンが合わず、疲れた顔に見える", stat: "存在感-10" },
      { item: "ゴールドアクセサリー", reason: "ブルーベースの肌に黄味の金属が浮き、チグハグな印象になる", stat: "色気-10" },
    ],
    celebrities: ["向井理", "福士蒼汰", "三浦春馬"],
    products: [
      {
        name: "ラベンダー シルクパジャマセット",
        description: "ブルベ夏の透明感を最大限に引き出すラベンダーカラー。ピンク味のある肌に青みの淡い色がなじみ、リラックスタイムも上品な印象に。誕生日ギフトに最適な高級シルク100%。",
        price: "¥28,000〜",
        affiliateUrl: "https://example.com/affiliate/summer-lavender-silk-pajama-gift",
        tag: "誕生日に",
      },
      {
        name: "ブルーグレー 本革トートバッグ",
        description: "ブルベ夏のスモーキーな魅力を引き立てるブルーグレーカラー。柔らかい肌色と調和するくすみブルーが、知的で洗練された雰囲気を演出。クリスマスの贈り物にふさわしい上質な本革仕立て。",
        price: "¥35,000〜",
        affiliateUrl: "https://example.com/affiliate/summer-bluegrey-leather-tote-gift",
        tag: "クリスマスに",
      },
      {
        name: "シルバー ブレスレットウォッチ",
        description: "ブルベ夏の肌に映えるシルバーカラー。青みのある肌とシルバーの冷たい光沢が美しく調和し、手元に透明感と品格をプラス。記念日に贈りたいエレガントな一本。",
        price: "¥22,000〜",
        affiliateUrl: "https://example.com/affiliate/summer-silver-bracelet-watch-gift",
        tag: "記念日に",
      },
    ],
    salonCta: {
      heading: "プロのカラー診断でベストカラーを見つける",
      description: "サマータイプは涼しげで柔らかいトーンが得意。プロの診断で、あなたに最適なラベンダーやブルーグレーの色味を見つけましょう。",
      buttonLabel: "近くのサロンを探す",
      url: "https://example.com/salon/color-diagnosis",
    },
  },
  autumn: {
    type: "autumn",
    label: "オータム（イエベ秋）",
    description: "深みのある暖かい色が似合う。落ち着いた大人の雰囲気を活かすカラーリング。",
    stats: { 存在感: 80, 清潔感: 65, 信頼感: 75, 色気: 85, 親しみ: 60 },
    features: [
      "肌に黄味がありマットな質感",
      "瞳が深みのあるダークブラウン",
      "アースカラーが映える",
      "アンティークゴールドが似合う",
    ],
    fashion: [
      { item: "カーキ・オリーブ", reason: "黄味がありマットな肌質とアースカラーが自然に溶け合い、落ち着いた色気が出る", stat: "色気+20" },
      { item: "テラコッタ・マスタード", reason: "深い肌色と深い暖色が共鳴し、大人の重厚感が増す", stat: "存在感+15" },
      { item: "ダークブラウン・チョコレート", reason: "瞳や髪のダークブラウンと統一感が出て、全体がまとまる", stat: "信頼感+15" },
      { item: "バーガンディ・ワインレッド", reason: "マットな肌に深い赤が品よく映え、落ち着いた華やかさが出る", stat: "清潔感+10" },
      { item: "ダークオレンジ", reason: "黄味ベースの肌色と最も相性が良く、顔色が生き生きと見える", stat: "親しみ+15" },
    ],
    ngItems: [
      { item: "パステルピンクやラベンダー", reason: "深い肌色に薄い青みカラーが浮き、ぼやけた印象になる", stat: "存在感-15" },
      { item: "ビビッドな青", reason: "黄味のある肌と鮮やかな青が激しく衝突し、肌がくすんで見える", stat: "清潔感-10" },
      { item: "真っ白", reason: "マットな肌との差が大きすぎて、白だけが目立ち顔が暗く沈む", stat: "色気-10" },
      { item: "シルバーアクセサリー", reason: "黄味肌にシルバーの冷たさが合わず、肌が灰色がかって見える", stat: "信頼感-15" },
    ],
    celebrities: ["竹野内豊", "長瀬智也", "松田翔太"],
    products: [
      {
        name: "カーキ 本革ボストンバッグ",
        description: "イエベ秋のマットな肌質と自然に溶け合うカーキカラー。深みのあるアースカラーが落ち着いた大人の色気を引き出し、旅行にも普段使いにも活躍。誕生日に贈りたい本格レザー仕様。",
        price: "¥32,000〜",
        affiliateUrl: "https://example.com/affiliate/autumn-khaki-leather-boston-gift",
        tag: "誕生日に",
      },
      {
        name: "テラコッタ カシミヤストール",
        description: "イエベ秋の深い肌色と共鳴するテラコッタカラー。顔まわりに巻けば黄味のある肌が生き生きと見え、重厚感のある大人の印象に。クリスマスギフトにぴったりの極上カシミヤ。",
        price: "¥24,000〜",
        affiliateUrl: "https://example.com/affiliate/autumn-terracotta-cashmere-stole-gift",
        tag: "クリスマスに",
      },
      {
        name: "アンティークゴールド 腕時計",
        description: "イエベ秋と最も相性が良いアンティークゴールド。黄味のある肌にゴールドの温かみが調和し、手元に品格と風格をプラス。記念日の特別な贈り物にふさわしい逸品。",
        price: "¥28,000〜",
        affiliateUrl: "https://example.com/affiliate/autumn-antique-gold-watch-gift",
        tag: "記念日に",
      },
    ],
    salonCta: {
      heading: "プロのカラー診断でベストカラーを見つける",
      description: "オータムタイプは深みのあるアースカラーが得意。プロの診断で、あなたに似合うカーキやテラコッタの最適なトーンを見つけましょう。",
      buttonLabel: "近くのサロンを探す",
      url: "https://example.com/salon/color-diagnosis",
    },
  },
  winter: {
    type: "winter",
    label: "ウィンター（ブルベ冬）",
    description: "鮮やかでコントラストの強い色が似合う。モダンで華やかな印象を活かすカラーリング。",
    stats: { 存在感: 85, 清潔感: 80, 信頼感: 75, 色気: 80, 親しみ: 50 },
    features: [
      "肌が青白く色白、もしくは褐色",
      "瞳がはっきりした黒",
      "モノトーンが映える",
      "プラチナ・シルバーが似合う",
    ],
    fashion: [
      { item: "ブラック・ピュアホワイト", reason: "色白でコントラストの強い肌に、はっきりした色が映えて存在感が出る", stat: "存在感+20" },
      { item: "ロイヤルブルー・ネイビー", reason: "青白い肌にブルー系が溶け込み、顔色が引き締まってシャープに見える", stat: "信頼感+15" },
      { item: "ワインレッド・フューシャピンク", reason: "ブルーベースの肌に鮮やかな赤系が映え、華やかさと品格が出る", stat: "色気+15" },
      { item: "シルバーグレー", reason: "冷たいトーンの肌色とシルバー系が調和し、都会的な印象になる", stat: "清潔感+15" },
      { item: "ビビッドな原色", reason: "コントラストの強い顔立ちが鮮やかな色に負けず、互いを引き立てる", stat: "親しみ+10" },
    ],
    ngItems: [
      { item: "ベージュ・キャメル", reason: "青白い肌に黄味の暖色が乗ると、肌がくすんで黄ばんで見える", stat: "清潔感-15" },
      { item: "くすんだパステルカラー", reason: "コントラストの強い顔が中間色に埋もれ、ぼんやりした印象になる", stat: "存在感-15" },
      { item: "オレンジ", reason: "ブルーベースの肌と正反対の色味で、肌が不健康に見える", stat: "信頼感-10" },
      { item: "アースカラー全般", reason: "冷たいトーンの肌とアーストーンが合わず、顔全体がくすむ", stat: "色気-10" },
    ],
    celebrities: ["松本潤", "山下智久", "平野紫耀"],
    products: [
      {
        name: "ブラック イタリアンレザー名刺入れ",
        description: "ブルベ冬のシャープな印象を最大限に活かす漆黒カラー。色白でコントラストの強い肌にブラックが映え、手元にモダンな存在感をプラス。誕生日に贈りたい上質イタリアンレザー。",
        price: "¥18,000〜",
        affiliateUrl: "https://example.com/affiliate/winter-black-leather-cardcase-gift",
        tag: "誕生日に",
      },
      {
        name: "ロイヤルブルー シルクネクタイ",
        description: "ブルベ冬の青白い肌に鮮やかに映えるロイヤルブルー。顔色を引き締めてシャープな印象を際立たせ、ビジネスシーンでも一目置かれる存在に。クリスマスに贈りたい極上シルク。",
        price: "¥15,000〜",
        affiliateUrl: "https://example.com/affiliate/winter-royalblue-silk-tie-gift",
        tag: "クリスマスに",
      },
      {
        name: "プラチナ カフリンクス",
        description: "ブルベ冬の肌に美しく調和するプラチナの光沢。冷たいトーンの肌色とプラチナの輝きが共鳴し、袖元に都会的な品格を添える。記念日の贈り物にふさわしい特別な一品。",
        price: "¥35,000〜",
        affiliateUrl: "https://example.com/affiliate/winter-platinum-cufflinks-gift",
        tag: "記念日に",
      },
    ],
    salonCta: {
      heading: "プロのカラー診断でベストカラーを見つける",
      description: "ウィンタータイプはビビッドな色やモノトーンが得意。プロの診断で、あなたに最適なブラックやロイヤルブルーの組み合わせを見つけましょう。",
      buttonLabel: "近くのサロンを探す",
      url: "https://example.com/salon/color-diagnosis",
    },
  },
};
